### ISSUE TITLE
Cascade delete not firing BEFORE/AFTER_DELETE hooks?

### ISSUE THREAD

**Issue by ognjenk** [rsinger86/django-lifecycle#89] opened 2021-11-22 19:20 UTC
Hi,
I have 2 models:

```
class Model_A(LifecycleModelMixin, models.Model):
    code = models.CharField(max_length=50)

class Model_B(LifecycleModelMixin, models.Model):
    code = models.CharField(max_length=50)
    model_a = models.ForeignKey(to="app.Model_A", on_delete=models.CASCADE, blank=True, null=True)

    @hook(AFTER_DELETE)
    def do_after_delete(self):
        print("AFTER_DELETE")

    @hook(BEFORE_DELETE)
    def do_before_delete(self):
        print("BEFORE_DELETE")
```

It seems like lifecycle hooks are not triggered when I delete one instance of Model_A which has a couple of Model_B children.
Hooks are normally triggered when I delete Model_B directly.

I am not doing SQL delete, rather I am triggering django instance delete by doing:

```
instance_a = Model_A.objects.get(code="ABC)
instance_a.delete()
```

My understanding is that this should fire delete signals, so I was expecting they would fire on cascade deleted instances as well.
Is this expected behaviour or am I doing something wrong?

Thanks in advance!

**Comment by vik-y** [comment] 2022-01-17 07:52
Was thinking of using this library in one of my projects. This one  seems to be a major problem. Did you figure it out yet?

**Comment by dmartin** [comment] 2022-09-02 03:13
This seems like expected behavior IMO. From the [Django documentation](https://docs.djangoproject.com/en/dev/topics/db/models/#overriding-predefined-model-methods):

> Note that the [delete()](https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.delete) method for an object is not necessarily called when [deleting objects in bulk using a QuerySet](https://docs.djangoproject.com/en/dev/topics/db/queries/#topics-db-queries-delete) or as a result of a [cascading delete](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ForeignKey.on_delete). To ensure customized delete logic gets executed, you can use [pre_delete](https://docs.djangoproject.com/en/dev/ref/signals/#django.db.models.signals.pre_delete) and/or [post_delete](https://docs.djangoproject.com/en/dev/ref/signals/#django.db.models.signals.post_delete) signals.

I wouldn't expect this library to automatically hook up a `post_delete` signal since its stated purpose is just to automate clunky manual overrides to model `.save()` / `.delete()` methods. But maybe the `*_DELETE` hooks should have some additional documentation explaining this limitation.

**Comment by EnriqueSoria** [comment] 2023-09-11 10:53
As @dmartin said, Django itself doesn't call `.delete()` neither it fires related django signals, so we can't provide a general enough solution that works for everyone.

As a workaround you could add a hook on your `Model_A` that calls your `Model_B` hooks.


I'm closing this issue. Feel free to reopen it if it's needed.

**Closed by EnriqueSoria** 2023-09-11 10:53 UTC
Labels: wontfix
