### ISSUE TITLE
Django 4.x support

### ISSUE THREAD

**Issue by Archmonger** [rsinger86/django-lifecycle#114] opened 2022-09-27 22:28 UTC
Currently, Django 4.x is not tested within `tox.ini`.

Best to update this and check if there are any bugs surrounding Django 4.

**Comment by peter-stuart-turner** [comment] 2023-03-23 19:51
There are - sometimes, after an AFTER_SAVE hook is triggered, a db_task is not able to access the object by PK.

Serious one - but not sure of the root cause, will be investigating it with @jacoduplessis

**Comment by jacoduplessis** [comment] 2023-03-24 13:02
> There are - sometimes, after an AFTER_SAVE hook is triggered, a db_task is not able to access the object by PK.
> 
> Serious one - but not sure of the root cause, will investigate it (perhaps with @jacoduplessis)

You need to add on_commit=True in your hook config. See #97.

**Closed** 2023-09-05 16:49 UTC
